version: '3.7'

services:
  sport-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: sport-app
    expose:
      - '8080'
    ports:
      - '8080:8080'
    command: yarn run dev
